/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User registration */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Access token refreshed */
                200: {
                    headers: {
                        Authorization?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MinimalSuccessResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user and invalidate refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get logged-in user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile fetched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initialize video upload
         * @description Creates a video record in INITIATED state. State transition: NONE → INITIATED.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InitVideoUploadRequest"];
                };
            };
            responses: {
                /** @description Upload initialized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InitVideoUploadResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Duplicate request or invalid state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get video metadata and status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Video details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VideoResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Video not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/signedurl/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get multipart upload signed URLs
         * @description Allowed only when video status = INITIATED. State transition: INITIATED → UPLOADING.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed URLs generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetSignedUrlResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Video not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid video state (must be INITIATED) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/complete/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete multipart upload
         * @description Allowed only when video status = UPLOADING. State transition: UPLOADING → PROCESSING. Transcoding and final processing occur asynchronously.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    videoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteVideoUploadRequest"];
                };
            };
            responses: {
                /** @description Upload completed and processing started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MinimalSuccessResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Video not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid video state (must be UPLOADING) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all videos of the logged-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of user's videos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            data?: components["schemas"]["GetMyVideosResponse"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MinimalSuccessResponse: {
            /** @example success */
            status: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        UserProfileResponse: {
            status?: string;
            data?: {
                id?: string;
                name?: string;
                email?: string;
            };
        };
        InitVideoUploadRequest: {
            title: string;
            description?: string;
            filename: string;
            /** @example 1073741824 */
            filesize: number;
            /** @enum {string} */
            filetype: "video/mp4" | "video/webm" | "video/mkv" | "video/mov";
        };
        InitVideoUploadResponse: {
            status: string;
            videoId: string;
        };
        GetSignedUrlResponse: {
            status?: string;
            data?: {
                signedUrls?: {
                    partNumber?: number;
                    /** Format: uri */
                    url?: string;
                }[];
            };
        };
        CompleteVideoUploadRequest: {
            parts: {
                partNumber?: number;
                eTag?: string;
            }[];
        };
        /** @description Video lifecycle is event-driven. INITIATED → UPLOADING → PROCESSING → READY/FAILED. State transitions are controlled by backend events. */
        VideoResponse: {
            id: string;
            title: string;
            description?: string | null;
            /** @enum {string} */
            status: "INITIATED" | "UPLOADING" | "PROCESSING" | "READY" | "FAILED";
            /** Format: uri */
            playbackUrl?: string | null;
            /** Format: uri */
            thumbnailUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        GetMyVideosResponse: {
            status?: string;
            data?: {
                videos?: components["schemas"]["VideoResponse"][];
                processingVideos?: components["schemas"]["VideoResponse"][];
                readyVideos?: components["schemas"]["VideoResponse"][];
                totalPages?: number;
                currentPage?: number;
            };
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Internal server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    Authorization?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinimalSuccessResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    Authorization: string;
                    cookie: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinimalSuccessResponse"];
                };
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
        };
    };
}
